# [options]
# ; Server Configuration
# admin_passwd = odoo_password
# db_host = localhost
# db_port = 5433
# db_user = odoo
# db_password = odoo_password

# ; Addons
# addons_path = /home/jojomojo/Desktop/Odoo16/addons, /home/jojomojo/Desktop/Odoo16/custom_addons

# ; Logging
# log_level = info
# logfile = /var/log/odoo/odoo.log

# ; Server Settings
# xmlrpc = True
# xmlrpc_port = 8068
# longpolling_port = 8072
[options]
; Server Configuration
admin_passwd = odoo_password
db_host = localhost
db_port = 5433
db_user = odoo
db_password = odoo_password

; Addons
addons_path = /home/jojomojo/Odoo16/addons, /home/jojomojo/Odoo16/custom_addons

; Logging
log_level = info
logfile = /var/log/odoo/odoo.log

; Server Settings
xmlrpc = True
xmlrpc_port = 8068
longpolling_port = 8072